#!/bin/bash

USAGE=$(cat <<-END

    USAGE: scripts/heroku <command> [<option> <option>...]

        commands:

            dburl       retrieves the fully-qualified URL for the database
            tail        start tailing the logs from the specified environment

        options:

            --prod      use the production environment instead of staging
END
)

# Command Functions ####################################################################################################

function dburl {
    heroku config:get DATABASE_URL --app $APP
}

function tail {
    heroku logs --tail --app $APP
}

function usage {
    echo "$USAGE"; echo
    exit 1
}

########################################################################################################################

COMMAND="$1"
shift

[[ "$COMMAND" == "" ]] && usage

if ! echo "$COMMAND" | egrep -q "dburl|tail"; then
    usage "Unknown command: $COMMAND"
fi

ENV="staging"
while [[ "$1" != "" ]]; do
    case $1 in
        "--prod") ENV="prod";;
        "-h") usage;;
    esac
    shift
done

[[ "$ENV" == "staging" ]] && APP="crafting-guide-staging"
[[ "$ENV" == "prod" ]] && APP="crafting-guide-production"

[[ "$COMMAND" == "" ]] && usage
$COMMAND
