#!/bin/bash

if ! which npm >/dev/null; then
    echo "FATAL: Please install Node.js on this machine!"
    exit 1
fi

if ! which nodemon >/dev/null; then
    echo "WARNING: nodemon not present! Installing..."
    npm install -g nodemon || exit 1
fi

clear
nodemon ./src/index.coffee $*
echo ''
